<a href="https://www.kaggle.com/code/pedro2318/pmr3508-2018-66f39f7a58-tarefa1?scriptVersionId=117503309" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

EP1- PMR3508-2018-66f39f7a58 Bases Adult e HouseholdIncome

In [1]:
import os
os.listdir('/kaggle/input/')

['sample_submission.csv',
 'train_data.csv',
 'test_data.csv',
 'Extra file from UCI.txt']

In [2]:
import pandas as pd
import sklearn
adult = pd.read_csv("/kaggle/input/train_data.csv",
        sep=r'\s*,\s*',
        engine='python',
        na_values="?")

In [3]:
adult.shape

(32560, 16)

In [4]:
adult.head()

      Id  age     workclass   ...    hours.per.week native.country  income
0  16280   34       Private   ...                44  United-States   <=50K
1  16281   58     Local-gov   ...                40  United-States   <=50K
2  16282   25       Private   ...                42  United-States   <=50K
3  16283   24       Private   ...                40  United-States   <=50K
4  16284   57  Self-emp-inc   ...                60        Hungary    >50K

[5 rows x 16 columns]

In [5]:
nadult = adult.dropna()

In [6]:
nadult.head()

      Id  age     workclass   ...    hours.per.week native.country  income
0  16280   34       Private   ...                44  United-States   <=50K
1  16281   58     Local-gov   ...                40  United-States   <=50K
2  16282   25       Private   ...                42  United-States   <=50K
3  16283   24       Private   ...                40  United-States   <=50K
4  16284   57  Self-emp-inc   ...                60        Hungary    >50K

[5 rows x 16 columns]

In [7]:
testAdult = pd.read_csv("/kaggle/input/test_data.csv",
        sep=r'\s*,\s*',
        engine='python',
        na_values="?")

In [8]:
nTestAdult = testAdult.dropna()

In [9]:
nTestAdult.head()

   Id  age       ...       hours.per.week  native.country
0   0   25       ...                   44   United-States
1   1   64       ...                   45   United-States
2   2   31       ...                   40   United-States
3   3   45       ...                   40   United-States
4   4   64       ...                   50   United-States

[5 rows x 15 columns]

In [10]:
Xadult = nadult[["age","education.num","capital.gain", "capital.loss", "hours.per.week"]]
Yadult = nadult["income"]
XtestAdult = nTestAdult[["age","education.num","capital.gain", "capital.loss", "hours.per.week"]]

In [11]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=3)
from sklearn.model_selection import cross_val_score
scores = cross_val_score(knn, Xadult, Yadult, cv=10)
knn.fit(Xadult,Yadult)
YtestPred = knn.predict(XtestAdult)

In [12]:
YtestPred

array(['<=50K', '>50K', '<=50K', ..., '<=50K', '<=50K', '>50K'],
      dtype=object)